### ISSUE TITLE
Write LA County Data vignette

### ISSUE THREAD

**Issue by shamindras** [shamindras/maars#13]
- [x] rewrite vignette using `comp_var`
- [x] Add [LA County Homeless data](http://www-stat.wharton.upenn.edu/~buja/STAT-961/Homeless_LA_by_Census_Tracts.csv) as part of our package, after checking with Arun and Andreas
- [x] Write a `vignette` demonstrating the use on the [LA County Homeless data](http://www-stat.wharton.upenn.edu/~buja/STAT-961/Homeless_LA_by_Census_Tracts.csv)
- [x] remove unnecessary packages from the first snippet
- [x] restructure sections
- [x] solve issues with citations
- [x] center tables

**Comment by ricfog** [comment]
Moved to #62
