### ISSUE TITLE
Add in Github Actions for benchmarks

### ISSUE THREAD

**Issue by shamindras** [shamindras/maars#17]
- [x] We should add in Github actions for benchmarks with the `bench` package e.g. [see here](https://raw.githubusercontent.com/tidyverse/dplyr/master/.github/workflows/continuous-benchmarks.yaml) for `dplyr` setup.
- [x] This is [still in an experimental stage](https://github.com/r-lib/bench#continuous-benchmarking), so we should examine the details of the `bench` package just prior to deploying this feature, particularly the `cb_fetch` function
- [x] Need to ensure that this works with `bench::press` and `bench::mark` since we use both these functions

**Comment by ricfog** [comment]
@shamindras please check whether this issue should be closed.

**Comment by shamindras** [comment]
@ricfog - thanks. Let's close it for now. We can re-create it during profiling later.
