### ISSUE TITLE
ENH: Fix Bootstrap Issues

### ISSUE THREAD

**Issue by shamindras** [shamindras/maars#25]
- [x] Fix the `sqrt(n)` scaling `multiplier_bootstrap` variance
- [x] check assumptions for empirical and multiplier bootstrap
- [x] add additional tests for the bootstrap
- [x] Fix the `sqrt(m)` scaling `empirical_bootstrap` variance. [Check this](https://github.com/shamindras/maars/blob/main/R/ols-boot-summary.R#L77)
- [x] Change `empirical` bootstrap to just generate indices inside `purrr::map` and only store the output `glm` or `lm` object
- [x] add testing for `residual` bootstrap
- [x] check the computation of the `statistic` in the `get_summary` function [here](https://github.com/shamindras/maars/blob/iss-38-rev-var-comp/R/ols-var.R#L58)
- [ ] ~~add testing for confidence intervals. Check why [this code](https://github.com/shamindras/maars/blob/f04db251d4f88cafe473d2ef345ef8d57dcdb82a/R/boot-empirical-var.R#L258) does not work for `stats::glm` in the testing [here](https://github.com/shamindras/maars/blob/f04db251d4f88cafe473d2ef345ef8d57dcdb82a/tests/testthat/test-boot-empirical-var.R#L64)~~
- [x] add testing for variance estimation and summaries
- [x] Add `residual` bootstrap
- [x] Remove default value of `B` in `empirical_bootstrap` variance
- [x] Fix the calculation of standard errors i.e. ensure that it is divided by `sqrt(n)`
- [x] compute covariance matrix in all types of bootstrap

**Comment by ricfog** [comment]
Experimental function for residual bootstrap.
```
comp_boot_res <- function(mod_fit, B = 100){
  
  # add check lm object
  
  res <- mod_fit$res
  n <- length(res)
  response_name <- as.character(formula(mod_fit)[2])
  data <- stats::model.frame(mod_fit)

  as.list(1:B) %>%
    purrr::map_df(
      ~ comp_cond_model(
        mod_fit = mod_fit,
        data = data %>% dplyr::mutate(!!sym(response_name) := !!sym(response_name) + sample(res, n, replace = T))
        #data = dplyr::mutate(data, {{response_name}} := {{response_name}} + sample(res, n, replace = T))
      ), .id = 'b'
    ) %>%
    tidyr::nest(data = c(term, estimate)) %>%
    dplyr::rename(boot_out = data) %>%
    dplyr::mutate(n = n) %>%
    dplyr::relocate(n)
  
}
```

**Comment by ricfog** [comment]
Experimental function for the residual bootstrap.

```
comp_boot_res <- function(mod_fit, B = 100){
  
  # add check lm object
  
  mod_res <- mod_fit$res
  mod_pred <- mod_fit$fitted.values
  n <- length(res)
  response_name <- as.character(formula(mod_fit)[2])
  data <- stats::model.frame(mod_fit)
  

  as.list(1:B) %>%
    purrr::map_df(
      ~ comp_cond_model(
        mod_fit = mod_fit,
        data = data %>% dplyr::mutate(!!sym(response_name) := mod_pred + sample(res, n, replace = T))
        #data = dplyr::mutate(data, {{response_name}} := {{response_name}} + sample(res, n, replace = T))
      ), .id = 'b'
    ) %>%
    tidyr::nest(data = c(term, estimate)) %>%
    dplyr::rename(boot_out = data) %>%
    dplyr::mutate(n = n) %>%
    dplyr::relocate(n)
  
}
```
