### ISSUE TITLE
ENH: Improve model diagnostics

### ISSUE THREAD

**Issue by ricfog** [shamindras/maars#34]
- [ ] @ricfog - add more testing for diagnostics
- [ ] @ricfog - add testing. Try the [vdiffr package](https://github.com/r-lib/vdiffr)
- [ ] @ricfog - allow user to feed their own set of weights into the function
- [ ] @ricfog - allow users to decide which objects should be added to the plots

**Comment by shamindras** [comment]
Moved to #58. We can create a new issue from there as needed.
