### ISSUE TITLE
FT: speed up the bootstrap functions

### ISSUE THREAD

**Issue by ricfog** [shamindras/maars#41]
- [ ] reuse the QR decomposition from `lm` in the regressions fitted in the residual bootstrap
- [ ] check whether the speed gap between our `comp_boot_emp` function and `covBS` from the `sandwich` package is worth justifying the use of that package. Note that `covBS` does not return the coefficients estimates
- [ ] sample rademacher weights with Rcpp in the multiplier bootstrap
- [ ] sample the indices in empirical and multiplier bootstrap in the same way and try sampling the indices in [a list](https://github.com/shamindras/maars/blob/7464e0aa961fe50089e7d88bf7a2d4171a06d19f/R/ols-boot-multiplier.R#L229)
- [x] in [`comp_boot_mul_wgt`](https://github.com/shamindras/maars/blob/7464e0aa961fe50089e7d88bf7a2d4171a06d19f/R/ols-boot-multiplier.R#L54), change `if` statement to `switch`  
- [x] transform the dataframe to tibble only once in `comp_boot_mul`
- [x] generate the datasets for the empirical bootstrap "on the fly" when calling `fit_reg` rather than storing them in a list by calling `comp_boot_emp_samples`

**Comment by shamindras** [comment]
Moved to #58. We can re-create it as necessary.
