### ISSUE TITLE
ENH: miscellaneous

### ISSUE THREAD

**Issue by ricfog** [shamindras/maars#48]
- [x] list of assumptions to be included in `summary` for `boot_emp`, `boot_res`, etc.
- [x] about how to deal with `tidy`, `glance`, and `augment` methods on `maars_lm`
- [x] set weights in `comp_var` for multiplier bootstrap by default to be rademacher
- [x] fix assumptions in estimators of the variance
- [x] add documentation in mss_var file
- [x] add documentation for methods
- [x] @Arun-Kuchibhotla: Add more specific citations in our documentation

**Comment by shamindras** [comment]
closed per commits
