### ISSUE TITLE
FT: Write vignettes

### ISSUE THREAD

**Issue by ricfog** [shamindras/maars#62]
- [x] vignette 1: linear regression lesson (from start to end)
- [x] vignette 2.1: consequence of misspecification on variance estimators and confidence intervals 
- [x] vignette 2.2: empirical coverage and average width of intervals under misspecification
- [x] vignette 3.1: effect of increasing B in (n-out-of-n) empirical / multiplier / (sqrt(n) out of n) subsampling bootstrap samples on coverage when compared to sandwich
- [x] vignette 3.2: effect of increasing m in m-out-of-n bootstrap/subsampling on coverage when compared to sandwich.

Items on vignette based on LA county data (partially inherited from #13):
- [x] remove unnecessary packages from the first snippet
- [x] solve issues with citations
- [x] center tables
- [x] remove explicit calls to packages (e.g., `ggplot2::` or `dplyr::`). Simply load all packages in a snippet in the beginning of the vignette
- [x] remove latex code (or move it to another vignette)

**Comment by Arun-Kuchibhotla** [comment]
Interesting datasets to include (not urgent at all, can be done after writing the vignettes):
Ames, Iowa housing dataset: https://www.tandfonline.com/doi/abs/10.1080/10691898.2011.11889627?src=recsys
                                               Dataset is available at http://www.amstat.org/publications/jse/v19n3/decock/AmesHousing.xls
                                               The description is available at http://jse.amstat.org/v19n3/decock/DataDocumentation.txt
This is an alternative to Boston housing data but without a clear motivating question to answer.
